# Move this to your root directory 


before_script:
  - apt-get update -qy #update system
  - ansible --version
  - ansible-lint --version
  - export ANSIBLE_HOST_KEY_CHECKING=False

stages:
  - verify
  - predeploy
  - deploy

verify:
  stage: verify
  script:
    - ansible-lint Ansible/plays/cloud-tenant-stretch-playbook.yml
    - ansible-playbook --inventory Ansible/inventory.ini --syntax-check Ansible/plays/cloud-tenant-stretch-playbook.yml
  rules:
    - if: '$CI_COMMIT_BEFORE_SHA ==  "0000000000000000000000000000000000000000"'
      when: always

predeploy:
  stage: predeploy
  script:
    - ansible --inventory Ansible/inventory.ini all -m ping --vault-password-file Ansible/vault-pass --connection httpapi
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always

deploy:
  stage: deploy
  script:
    - ansible-playbook --inventory Ansible/inventory.ini Ansible/plays/cloud-tenant-stretch-playbook.yml --vault-password-file Ansible/vault-pass
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: manual
