before_script:
  - apt-get update -qy #update system
  - ansible --version
  - ansible-lint --version
  - export ANSIBLE_HOST_KEY_CHECKING=False

stages:
  - verify
  - predeploy
  - deploy

verify:
  stage: verify
  script:
    - ansible-lint Ansible/task2.3/plays/task2.3.yml
    - ansible-playbook --inventory inventory.ini --syntax-check task2.3/plays/task2.3.yml
  rules:
    - if: '$CI_COMMIT_BEFORE_SHA ==  "0000000000000000000000000000000000000000"'
      when: always

predeploy:
  stage: predeploy
  script:
    - ansible --inventory Ansible/task2.3/inventory.ini all -m ping --vault-password-file task2.3/vault-pass --connection httpapi
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always

deploy:
  stage: deploy
  script:
    - ansible-playbook --inventory Ansible/task2.3/inventory.ini task2.3/plays/task2.3.yml --vault-password-file task2.3/vault-pass
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: manual
